### ISSUE TITLE
Add examples to datasets

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#147]
## Description of the problem
Currently all datasets are missing examples.

## Description of a solution
Add examples to all dataset classes.
Add a doctest instruction to skip some of (or all) the examples as the datasets must not be downloaded for each test run.

The examples should show how to load in the datasets.
Also all methods in the base classes should get examples.

## Minimum acceptance criteria
- [ ] Add examples to `datasets.Dataset`
- [ ] Add examples to `datasets.PublicDataset`
- [x] Add examples to `datasets.JuDo1000`
- [x] Add examples to `datasets.GazeBase`

**Comment by dkrako** [comment]
#162 adds examples to JuDo1000 and GazeBase

**Comment by SiQube** [comment]
we added documentation examples within each docstring. PublicDataset and Dataset are out of date.
