### ISSUE TITLE
Integrate Identification by Dispersion-Threshold (I-DT)

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#19]
## Description of the problem
The quite simple algorithm is defined here:
https://dl.acm.org/doi/10.1145/355017.355028
There exist several implementations of this on the internet where you can get inspiration.

## Description of a solution
- [x] implement basic algorithm
- [ ] create synthetic test data and test for expected result

## Minimum acceptance criteria
- [ ] passing tests with synthetic test data

**Comment by jakobchwastek** [comment]
Should we offer different dispersion metrics to use? Paper gives the following metric as example:
`D = [max(x) - min(x)] +[max(y) - min(y)]. `

**Comment by jakobchwastek** [comment]
add stride parameter

**Comment by jakobchwastek** [comment]
Still missing:
- [ ] Add documentation for errors
