### ISSUE TITLE
implement existing test stubs in test_base and test_checks

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#2]
The docstring should be sufficient to know what should be tested.
Feel free to add more tests.

**Comment by SiQube** [comment]
this issue is closed by several PRs in milestone 0.1, right?

**Comment by dkrako** [comment]
I don't know exactly, but I think some are still only tested via examples or indirectly.

**Comment by dkrako** [comment]
as full coverage is met either way, do we want to close as wontfix?

**Comment by SiQube** [comment]
I also vote for it, but we should have full agreement among codeowners -- @prassepaul?

**Comment by dkrako** [comment]
2/3 majority with one abstention :D
