### ISSUE TITLE
Integrate Identification by Velocity Threshold (I-VT)

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#20]
## Description of the problem
The quite simple algorithm is defined here:
https://dl.acm.org/doi/10.1145/355017.355028
There exist several implementations of this on the internet where you can get inspiration.

## Description of a solution
- [x] implement basic algorithm
- [ ] create synthetic test data and test for expected result

## Minimum acceptance criteria
- [ ] passing tests with synthetic test data

**Comment by jakobchwastek** [comment]
Missing:

- [ ] Add documentation for errors
