### ISSUE TITLE
rename tests from test_filename.py to filename_test.py

### ISSUE THREAD

**Issue by SiQube** [aeye-lab/pymovements#248]
## Description of the problem
some people, including me, work in the terminal. for people working in the terminal, tab complete is very handy. when all tests are named test_filename.py you have to tab-complete twice (i.e. if there is more than one file, and you have to tab-complete t tab f tab)

## Description of a solution
- Rename tests
- Include steps of the proposed solution.
  - rename all tests from test_filename.py to filename_test.py

- What are the expected benefits/improvements from working on this new feature?
the benefits for terminal users: tab complete

- Insert a clear and concise description of any alternative solutions or features you've considered.
n/a

## Minimum acceptance criteria
- [x] rename tests
- [x] check that coverage is the same

**Comment by dkrako** [comment]
yes we can do that if you want :+1:
