### ISSUE TITLE
automatically add `from __future__ import annotations`

### ISSUE THREAD

**Issue by SiQube** [aeye-lab/pymovements#280]
## Description of the problem
for a few pull requests we ran into the issue that in new files contributers forget to add `from __future__ import annotations`, e.g. #276. 

one possibility would be to add it automatically via `pre-commit`.

## Description of a solution

there is an easy fix: 
```diff
$ git diff .pre-commit-config.yaml
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index ce8a698..1fff6ca 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -16,7 +16,7 @@ repos:
     rev: v3.9.0
     hooks:
     -   id: reorder-python-imports
-      args: [--application-directories=.:src, --py37-plus, --add-import, 'from __future__ import annotations']
+        args: [ "--application-directories=.:src" , --py37-plus, --add-import, 'from __future__ import annotations']
 -   repo: https://github.com/pappasam/toml-sort
     rev: v0.22.4
     hooks:
```
## Minimum acceptance criteria

- [ ] run linter

## Sample Code
see solution above

## Context

see problem description

**Comment by SiQube** [comment]
if you think we should add this I can make a PR

**Comment by dkrako** [comment]
perfect let's do this!
