### ISSUE TITLE
Implement scanpath plot

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#30]
## Description of the problem
Eye tracking researchers often do a scanpath plot to see where fixations occurred and what their sequence was.

## Description of a solution
- [ ] implement plotting function
- [ ] create an example notebook to visualize this plotting function

## Minimum acceptance criteria
- [ ] example notebook that demonstrates plotting function

**Comment by dkrako** [comment]
integrate stimulus

**Comment by SiQube** [comment]
resolved via #782
