### ISSUE TITLE
Groupby in transformation and event detection functionality

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#382]
## Description of the problem
Currently the gaze dataframes are not grouped by trials.

This is problematic, as recording is potentially interrupted between trials.

For example, when transforming positional data into velocity data, this will create artifacts with very high velocity between each trial as the position changes instantly. 

## Description of a solution
This can be mitigated using a `groupby` argument to the gaze transformations and event detection functions.

For the `Dataset` class this could be done implicitly (maybe with the ability to specify/override optionally?) by a new attribute in the `DatasetDefinition` class.

## Minimum acceptance criteria
- [x] add `groupby` argument in the transformation functions in the `GazeDataFrame` class.
- [x] add `groupby` attribute to `DatasetDefinition`
- [x] use `groupby` attribute of `DatasetDefinition` for the transformation in the `Dataset` class
- [x] use `groupby` attribute of `DatasetDefinition` for the event detection methods in the `Dataset` class

**Comment by jakobchwastek** [comment]
Yes please! Additionally, the values of the trial columns are missing for the gaze data within the resulting EventDataFrame.

**Comment by dkrako** [comment]
Closed by #655
