### ISSUE TITLE
raise warning if subset not in dataset

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#397]
## Description of the problem
When we specify a subset using `Dataset.load(subset=custom_subset)` it could be that the subset does not exist in the dataset.
For example, a subset could specify `{session_id: 5}` but there is no session 5 in the dataset files anywhere.
Currently this would result in no loaded files.

## Description of a solution
Instead it would be much nicer to either raise an error or at least a warning that the subset does not exist.

## Minimum acceptance criteria
- [ ] raise error or warning if subset does not exist

**Comment by josephine-funken** [comment]
`Dataset._check_fileinfo` already raises an error and the empty dataset is loaded.
