### ISSUE TITLE
integrate mypy into github workflow

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#41]
## Description of the problem
We have typehints so we can use them

## Description of a solution
integrate mypy into github workflow

**Comment by dkrako** [comment]
The following steps are necessary:

- [ ] add mypy to tox environments: https://github.com/aeye-lab/pymovements/blob/main/tox.ini
- [ ] add mypy to gitworkflow checks: https://github.com/aeye-lab/pymovements/blob/ad9c0174b22aa98a0048063622d2c45ca313bc07/.github/workflows/tests.yml#L50
- [ ] fix all the warnings and errors that come from adding mypy to the CI

**Comment by SiQube** [comment]
we could solve this using pre-commit, see #67

**Comment by dkrako** [comment]
I think actually it's the other way around.
We need mypy in a transparent way in the github workflow, otherwise reviewers have to run it themselves or trust that the author didn't use `--no-verify`.

**Comment by SiQube** [comment]
no -- actually pre-commit-ci can do it for us :-) runtime way faster

**Comment by dkrako** [comment]
I forgot to add the hard requirement for this issue, that this needs to be integrated into the tox pipeline.
We use the tox environment to be able to run all tests (including all supported python versions) locally.
By simply calling `tox` you can automatically run all necessary tests on your local machine (this will be including mypy).

So for consistency, all definitions are required to be in the `tox.ini` file.
Otherwise, developers are needed to run two different commands to check if all tests are passing for the current working state.
To run all `mypy` checks you would then just call `tox -e mypy`.

If you want pymovements to switch to another testing environment, please create a new issue for this, as it is out of scope with this specific issue.
I'm open to suggestions and that will be a better place to discuss further about what alternative solutions there are.
If we decide to switch, we can then move all the definitions from the `tox.ini` to a new system.

**Comment by dkrako** [comment]
done in #68

**Comment by SiQube** [comment]
as seen in PR #198 we run mypy twice, should we remove mypy from tox? pre-commit can also run locally

**Comment by dkrako** [comment]
As I have already encountered a bug where pre-commit.ci didn't run correctly I would be against it
