### ISSUE TITLE
order of calculating event properties makes a difference in results

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#417]
## Description of the problem
This is a major bug which I just found today while I tried to fix the strange plot in the 10-minutes tutorial in #416 

If calculating `peak_velocity` first and then `dispersion` and `amplitude` the results were completely messed up.

This changed when I calculated `dispersion` first and after that `peak_velocity`  and `amplitude`.
This is crazy and should never happen.

**Comment by SiQube** [comment]
can you provide a minimal script to reproduce the bug?

**Comment by dkrako** [comment]
was closed in #425
