### ISSUE TITLE
Add support for variable eye-to-screen distance

### ISSUE THREAD

**Issue by jakobchwastek** [aeye-lab/pymovements#495]
## Description of the problem
The setup of most eyetracking experiments includes the usage of a chin rest, which ensures a constant eye-to-screen distance. However, in remote eyetracking scenarios, the distance between the eye and screen can vary over time and is recorded as part of the dataset.
The current Experiment and Dataset definiton only supports static eye-to-screen distance for the entire dataset/experiment. This limits the ability to accuratly process data from remote eyetracking experiments where eye-to-screen distance can vary from sample to sample.

## Description of a solution
As far as I know the following components need to be adjusted:
- Dataset Specification: Include an option to specify a distance column within the dataset.
- Experiment Class: Modify the Experiment class to allow for a `None` value in the distance_cm argument, triggering a check for a specified distance column.
- Pixel-to-Degree Conversion: Update the `pix2deg` method to dynamically use the distance column if available.

## Minimum acceptance criteria
- [ ] allow users to specify a distance column in the dataset and gaze dataframe
- [ ] handle `distance_cm` argument in Experiment class
- [ ] `pix2deg` method must be modified to use the dynamic distance values from the distance column if available
- [ ] Add tests for new functionality
- [ ] Update documentation

**Comment by dkrako** [comment]
This is a great idea!

I think starting with extending the `gaze.transforms.pix2deg` function is most reasonable.
The keyword argument `distance` currently only supports float.
It could be changed to `distance: float | str` and if it's a string, then we would get the column from the dataframe.

**Comment by jakobchwastek** [comment]
I ran into a problem making `distance_cm` oprional in `gaze.Screen` class. The class currently computes the minimum and maximum dva values in the constructor. To perform this calculation `distance_cm` value is required.
Additionally, the numpy based `pix2deg` which this class allows to access relies on `distance_cm`.
Should we maybe drop the `pix2deg` method in this class and compute min/max dva values on demand with raising an error if no `distance_cm` specified?
