### ISSUE TITLE
Add test csv files for GazeBase and JuDo1000

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#569]
## Description of the problem
A prerequisite for working on #492 is that we have test data available that is similar to the data in each dataset.

## Description of a solution
Create small example files for each dataset.

Each file should contain the same header as in the original, but the rows should be limited to 10.

## Minimum acceptance criteria
- [x] `gazebase_example.csv` in `tests/gaze/io/files`
- [x] `gaze_on_faces_example.csv` in `tests/gaze/io/files`
- [x] `gazebase_vr_example.csv` in `tests/gaze/io/files`
- [x] `judo1000_example.csv` in `tests/gaze/io/files`
- [x] `hbn_example.csv` in `tests/gaze/io/files`
- [x] `sbsat_example.csv` in `tests/gaze/io/files`
- [x] add test cases to `tests/gaze/io/csv_test.py`

**Comment by SiQube** [comment]
why do we want to specificly tests judo and gazebase, or will we do similar things for every dataset?

**Comment by dkrako** [comment]
I think we should do that for every dataset.

In #492 we will implement a fixture to create GazeDataFrame instances from these files.
These can be then used in acceptance / functional tests (instead of unit testing), i.e. we will define short user stories and check outcomes on a higher level. Column and schema checking should be mostly sufficient, as the specific validity of the results must be tested in unit tests. 

As long as we don't solve the problem for caching public datasets, this is the best way I can think of to automatically test our pipeline.

This way I guess as a byproduct we will identify a test case that reproduces #517 in a functional test.
