### ISSUE TITLE
"Edit on Github" button on readthedocs doesn't work for all pages

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#66]
## Expected Behavior
Usually when you click on the "Edit on Github" on a readthedocs page, you should be forwarded to the particular .rst file which defines the page.

## Current Behavior

In some cases, the .rst file doesn't exist and an 404 error is raised.

## Minimum acceptance criteria

There should be no link of that type in the docs which raises an 404 error.

## Failure Information (for bugs)

I think the problem is, that some of the rst files are autogenerated and put into gitignore.
That way they are not present in the repository.

So there could be two solutions for this issue:
- remove this link completely from the documentation page
- add the generated rst files to the repository

### Steps to Reproduce

Here's an example page:
https://pymovements.readthedocs.io/en/stable/reference/pymovements.paths.html

- click on "Edit on Github" on the upper right of the page
- see a 404 file doesn't exist error in the pymovements repo

**Comment by SiQube** [comment]
I think this issue is resolved -- at least I couldn't find any links that do no work

**Comment by dkrako** [comment]
yes you're right, the "Edit on GitHub" button doesnt seem to be a part of the template
