### ISSUE TITLE
add tutorial on how to add new datasets

### ISSUE THREAD

**Issue by dkrako** [aeye-lab/pymovements#692]
## Description of the problem
Currently there is not a step by step guideline on how to contribute datasets to the dataset library.

## Description of a solution
Although the contributing.md is a good place to start adding this information, I think it would be best to link from there to a tutorial in our readthedocs page.

The CONTRIBUTING.md could include a link and maybe some more broad description, that we provide a metalibrary of downloadable datasets which are not hosted / provided by us but downloadable via pymovements. More general advices could also be included, like that a fork needs to be created if there's no invite for developing privileges yet.

What the CONTRIBUTING.md could also include is how to test the dataset via tox:

```
tox -e integration -- tests/integration/public_dataset_processing_test.py::test_public_dataset_processing[PoTeC]
```

## Minimum acceptance criteria
- [ ] add dataset contribution step by step guide to CONTRIBUTING.md

**Comment by SiQube** [comment]
I close this in favour of #379. we also have to think about this when merging #771
