### ISSUE TITLE
`position_column` and `velocity_column` kwargs ignored in `EventPropertyProcessor`

### ISSUE THREAD

**Issue by saeub** [aeye-lab/pymovements#735]
## Current Behavior

When using `compute_event_properties(("location", {"position_column": "pixel"})`, the provided `position_column` kwarg has no effect, because it is replaced with the default value here:
https://github.com/aeye-lab/pymovements/blob/cb32c39f0b8a848372a6dcc10c4e3db0bbf26355/src/pymovements/events/processing.py#L191-L198

## Expected Behavior

I would expect kwargs like `position_column` or `velocity_column` to be passed through to the event properties. Could the code snippet above just be removed, since properties like `location` or `peak_velocity` already have a default value defined in their function signature anyway?
https://github.com/aeye-lab/pymovements/blob/cb32c39f0b8a848372a6dcc10c4e3db0bbf26355/src/pymovements/events/properties.py#L197-L203

## Minimum acceptance criteria

Either remove the snippet where the default value is set in `processing.py`, or check if the user provided a value for these kwargs before replacing them.

## Context

Please provide any relevant information about your setup.
This is important in case the issue is not reproducible except for under certain conditions.

* Project Version / Commit: cb32c39f0b8a848372a6dcc10c4e3db0bbf26355
* Operating System: Linux

## Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information for the team

**Comment by SiQube** [comment]
resolved via #760
