### ISSUE TITLE
Event detection fails for datasets with Int32 trial columns

### ISSUE THREAD

**Issue by saeub** [aeye-lab/pymovements#750]
## Current Behavior

```
import pymovements as pm
dataset = pm.Dataset("SBSAT", "sb-sat").load()
dataset.pix2deg().pos2vel().detect("ivt")
```

Raises: `SchemaError: cannot extend/append Int32 with Int64`

The reason for this is that the SB-SAT dataset uses `Int32` for the trial column `screen_id` column: https://github.com/aeye-lab/pymovements/blob/1e2eac18c5bd53f5a9ca2c3d679adc3eb4613964/src/pymovements/datasets/sb_sat.py#L148

But when events are detected, all integer columns are casted to `Int64`:
https://github.com/aeye-lab/pymovements/blob/1e2eac18c5bd53f5a9ca2c3d679adc3eb4613964/src/pymovements/events/frame.py#L237-L244

## Expected Behavior

Event detection should either allow non-Int64 integer values, or dataset definitions should enforce Int64 for trial columns in the dataset definition.

## Context

* Project Version / Commit: 1e2eac18c5bd53f5a9ca2c3d679adc3eb4613964
* Operating System: Linux

## Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I have provided sufficient information for the team

**Comment by saeub** [comment]
I'm happy to create a PR to fix this, I'm just not sure what the reasoning behind [enforcing Int64 columns for integers](https://github.com/aeye-lab/pymovements/blob/1e2eac18c5bd53f5a9ca2c3d679adc3eb4613964/src/pymovements/events/frame.py#L240) was, so I don't know what the best way to fix it is.

**Comment by SiQube** [comment]
me neither -- how about @prassepaul do you know?

**Comment by SiQube** [comment]
maybe we can just cast to Int32?

**Comment by SiQube** [comment]
code to reproduce from scratch:

```python
import pymovements as pm
dataset = pm.Dataset("SBSAT", "sb-sat").download()
dataset.load().pix2deg().pos2vel().detect("ivt")
```

**Comment by prassepaul** [comment]
I think since we are using Int64 in most of the datasets, its saver to just change the dataset definition to Int64.
