### ISSUE TITLE
Allow custom patterns for extracting logged metadata from ASC files

### ISSUE THREAD

**Issue by saeub** [aeye-lab/pymovements#758]
## Description of the problem

Currently, the `from_asc()` only supports custom regex patterns via the `patterns` argument, which adds the captured values to columns in the dataframe. It would be useful if we could also extract session-level metadata (e.g., the stimulus randomization order, which we log in the ASC file).

## Description of a solution

1. Add another argument to `from_asc()` (e.g., `metadata_patterns`) that accepts custom regular expressions. The captured values should be added to the metadata dictionary returned by `parse_eyelink()`.
2. Return the metadata dictionary from `from_asc()`.

## Sample Code

```py
>>> data, metadata = pm.gaze.from_asc("foo.asc", metadata_patterns=[r"stimulus order: (?P<stimulus_order>.+)"])
>>> metadata
{"stimulus_order": "order1", ...}
```

The code should probably either warn the user in case there are multiple logged messages that match the pattern, or collect all of them in a list (e.g., `{"stimulus_order": ["order1", "order2"], ...}`)

**Comment by SiQube** [comment]
related to #510
