### ISSUE TITLE
Metadata Documentation

### ISSUE THREAD

**Issue by faizygithub** [aeye-lab/pymovements#868]
## Description of the problem
Currently, the metadata structure we receive after recording is poorly organized, making it difficult to interpret the various pieces of information.

## Description of a solution
We aim to document this information in a clear, structured format to ensure it is easy to read and understand 

Include steps of the proposed solution.
 -Create a class that will organize the metadata in a more structured and meticulous manner

What are the expected benefits/improvements from working on this new feature?
This feature will centralize metadata information, making it easier to access and manage.

## Sample Code

```py
>>> gazeframe, metadata = from_asc(...)
>>> metadata.tracked_eye
'right'
>>> metadata.calibrations
[...]
```

The metadata could also be part of the gazeframe (gazeframe.metadata).

**Comment by dkrako** [comment]
It would be great if you could pass the metadata to the [`Experiment`](https://github.com/aeye-lab/pymovements/blob/main/src/pymovements/gaze/eyetracker.py) / [`EyeTracker`](https://github.com/aeye-lab/pymovements/blob/main/src/pymovements/gaze/experiment.py) class.

In case an `Experiment` is passed to `from_asc()`, it would probably be best to create a copy before filling it with parsed metadata.
