### ISSUE TITLE
Verbosity options

### ISSUE THREAD

**Issue by jakobchwastek** [aeye-lab/pymovements#94]
## Description of the problem

I'm always frustrated when processing data with long running algorithms, and there is no indication of the progress or status of the process.

## Description of a solution

I propose adding a verbosity option to the algorithms, which will allow users to see the progress of the algorithm, maybe using something like tqdm. This will provide the user with a better sense of how long the process is taking, and when it should be completed.

## Minimum acceptance criteria

- Decide on a common practice for handling verbosity
- Implement the verbosity option in the algorithms

**Comment by dkrako** [comment]
Good idea, we will use tqdm for this as I already used it for the new dataset downloading class and the preprocessing there. we will have to discuss if it makes sense to put it in the algorithms themselves or rather in the processing pipeline.

**Comment by dkrako** [comment]
most of the issue should be already addressed in previous PRs and more recently in #349 

let's create new feature requests in case there should be some specific function or method which should have more verbose output or progress bars
